[data]
stop_words_eng = ../data/raw/stop_words_eng.txt
stop_words_zh = ../data/raw/stop_words_zh.txt
english = ../data/raw/EN/english.txt
bible = ../data/raw/EN/The_Holy_Bible.txt
chinese_dir = ../data/raw/CN/art/

[output]
output_dir = ../data/output/
en_dict = en_dict.dat
en_index = en_index.dat
cn_dict = cn_dict.dat
cn_index = cn_index.dat
