# conf/word.conf
[data]
path = data/
suffix = .txt

[dict]
english = english.txt
chinese = art/
holy_bible = The_Holy_Bible.txt

[jieba]
dict = include/cppjieba/dict/jieba.dict.utf8
hmm = include/cppjieba/dict/hmm_model.utf8
user = include/cppjieba/dict/user.dict.utf8
idf = include/cppjieba/dict/idf.utf8
stop_word = include/cppjieba/dict/stop_words.utf8

[output]
en_dict = en_dict
en_index = en_index
cn_dict = cn_dict
cn_index = cn_index
