pagelib = ../../offline/page/data/output/pagelib.dat
offsetlib = ../../offline/page/data/output/offsetlib.dat
indexlib = ../../offline/page/data/output/indexlib.dat

dict = ../../third_party/cppjieba/dict/jieba.dict.utf8
hmm = ../../third_party/cppjieba/dict/hmm_model.utf8
user = ../../third_party/cppjieba/dict/user.dict.utf8
idf = ../../third_party/cppjieba/dict/idf.utf8
stop_word = ../../third_party/cppjieba/dict/stop_words.utf8

stop_words_zh = ../../offline/page/data/raw/stop_words_zh.txt
search_topk = 5

en_dict = ../../offline/word/data/output/en_dict.dat
en_index = ../../offline/word/data/output/en_index.dat
cn_dict = ../../offline/word/data/output/cn_dict.dat
cn_index = ../../offline/word/data/output/cn_index.dat
topk = 5
