raw_data_dir = ../data/raw/
pdo_xml_dir = ../data/raw/pdo_predicts/
output_dir = ../data/output/

dict = ../../../third_party/cppjieba/dict/jieba.dict.utf8
hmm = ../../../third_party/cppjieba/dict/hmm_model.utf8
user = ../../../third_party/cppjieba/dict/user.dict.utf8
idf = ../../../third_party/cppjieba/dict/idf.utf8
stop_word = ../../../third_party/cppjieba/dict/stop_words.utf8
